version: "3.7"
   
services:
  dj_tour:
    container_name: dj_tour
    volumes:
      - static:/static
    build:
      dockerfile: DockerFile
      context: .
    command: python manage.py runserver 192.168.200.15:8010
    ports: 
      - "8010:8010"
volumes:
  static: