version: "3"
   
services:
  
  dj_tour:
    container_name: dj_tour
    build: .
    command: python manage.py runserver 0.0.0.0:8010
    ports: 
      - "8010:8010"
    volumes: 
      - ./IUCA_tour:/IUCA_tour
  
    
  

