version: "3.7"
   
services:
  dj_tour:
    container_name: dj_tour
    volumes:
      - static:/static
    build: .
      dockerfile: DockerFile
      context: .
    ports: 
      - "8010:8010"
volumes:
  static: