version: "3"
   
services:
  
  dj_tour:
    container_name: dj_tour
    build: .
      dockerfile: DockerFile
      context: .
    ports: 
      - "8010:8010"
    volumes: 
      - ./IUCA_tour:/IUCA_tour
      - static:/static
volumes:
  static: