version: "3.7"
   
services:
  dj_tour:
    container_name: dj_tour
    volumes:
      - static:/static
    build:
      dockerfile: DockerFile
      context: .
    ports: 
      - "8010:8010"
      -
  nginx:
    build:
      context: ./nginx
      dockerfile: DockerFile
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - config
volumes:
  static: